<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita52d02af8e2c776d56aa5688365f6815
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'SleekDB\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'SleekDB\\' => 
        array (
            0 => __DIR__ . '/..' . '/rakibtg/sleekdb/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita52d02af8e2c776d56aa5688365f6815::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita52d02af8e2c776d56aa5688365f6815::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInita52d02af8e2c776d56aa5688365f6815::$classMap;

        }, null, ClassLoader::class);
    }
}
